//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("FoldDBModel", "fke", "Fold", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoldMannger.Fold), "file", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoldMannger.file), true)]

#endregion

namespace FoldMannger
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class FoldDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“FoldDBEntities”部分中的连接字符串初始化新 FoldDBEntities 对象。
        /// </summary>
        public FoldDBEntities() : base("name=FoldDBEntities", "FoldDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FoldDBEntities 对象。
        /// </summary>
        public FoldDBEntities(string connectionString) : base(connectionString, "FoldDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FoldDBEntities 对象。
        /// </summary>
        public FoldDBEntities(EntityConnection connection) : base(connection, "FoldDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<file> file
        {
            get
            {
                if ((_file == null))
                {
                    _file = base.CreateObjectSet<file>("file");
                }
                return _file;
            }
        }
        private ObjectSet<file> _file;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Fold> Fold
        {
            get
            {
                if ((_Fold == null))
                {
                    _Fold = base.CreateObjectSet<Fold>("Fold");
                }
                return _Fold;
            }
        }
        private ObjectSet<Fold> _Fold;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 file EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTofile(file file)
        {
            base.AddObject("file", file);
        }
    
        /// <summary>
        /// 用于向 Fold EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFold(Fold fold)
        {
            base.AddObject("Fold", fold);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoldDBModel", Name="file")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class file : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 file 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="fileName">fileName 属性的初始值。</param>
        /// <param name="filePath">filePath 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="foldId">FoldId 属性的初始值。</param>
        public static file Createfile(global::System.Int32 id, global::System.String fileName, global::System.String filePath, global::System.Int32 userId, global::System.Int32 foldId)
        {
            file file = new file();
            file.Id = id;
            file.fileName = fileName;
            file.filePath = filePath;
            file.UserId = userId;
            file.FoldId = foldId;
            return file;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fileName
        {
            get
            {
                return _fileName;
            }
            set
            {
                OnfileNameChanging(value);
                ReportPropertyChanging("fileName");
                _fileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fileName");
                OnfileNameChanged();
            }
        }
        private global::System.String _fileName;
        partial void OnfileNameChanging(global::System.String value);
        partial void OnfileNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String filePath
        {
            get
            {
                return _filePath;
            }
            set
            {
                OnfilePathChanging(value);
                ReportPropertyChanging("filePath");
                _filePath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("filePath");
                OnfilePathChanged();
            }
        }
        private global::System.String _filePath;
        partial void OnfilePathChanging(global::System.String value);
        partial void OnfilePathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoldId
        {
            get
            {
                return _FoldId;
            }
            set
            {
                OnFoldIdChanging(value);
                ReportPropertyChanging("FoldId");
                _FoldId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FoldId");
                OnFoldIdChanged();
            }
        }
        private global::System.Int32 _FoldId;
        partial void OnFoldIdChanging(global::System.Int32 value);
        partial void OnFoldIdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoldDBModel", "fke", "Fold")]
        public Fold Fold
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fold>("FoldDBModel.fke", "Fold").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fold>("FoldDBModel.fke", "Fold").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fold> FoldReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fold>("FoldDBModel.fke", "Fold");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fold>("FoldDBModel.fke", "Fold", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoldDBModel", Name="Fold")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fold : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Fold 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        public static Fold CreateFold(global::System.Int32 id, global::System.Int32 userId)
        {
            Fold fold = new Fold();
            fold.Id = id;
            fold.UserId = userId;
            return fold;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FoldName
        {
            get
            {
                return _FoldName;
            }
            set
            {
                OnFoldNameChanging(value);
                ReportPropertyChanging("FoldName");
                _FoldName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FoldName");
                OnFoldNameChanged();
            }
        }
        private global::System.String _FoldName;
        partial void OnFoldNameChanging(global::System.String value);
        partial void OnFoldNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FatherId
        {
            get
            {
                return _FatherId;
            }
            set
            {
                OnFatherIdChanging(value);
                ReportPropertyChanging("FatherId");
                _FatherId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FatherId");
                OnFatherIdChanged();
            }
        }
        private Nullable<global::System.Int32> _FatherId;
        partial void OnFatherIdChanging(Nullable<global::System.Int32> value);
        partial void OnFatherIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Depth
        {
            get
            {
                return _Depth;
            }
            set
            {
                OnDepthChanging(value);
                ReportPropertyChanging("Depth");
                _Depth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Depth");
                OnDepthChanged();
            }
        }
        private Nullable<global::System.Int32> _Depth;
        partial void OnDepthChanging(Nullable<global::System.Int32> value);
        partial void OnDepthChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoldDBModel", "fke", "file")]
        public EntityCollection<file> file
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<file>("FoldDBModel.fke", "file");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<file>("FoldDBModel.fke", "file", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
