//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34011 版自动生成。
// 
#pragma warning disable 1591

namespace WEBSericesTest.com._10628106.client {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://10628106.com/bus")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getBusLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTodayLineInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBusDepartureScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBusLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBusLineOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WEBSericesTest.Properties.Settings.Default.WEBSericesTest_com_10628106_client_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getBusLocationCompletedEventHandler getBusLocationCompleted;
        
        /// <remarks/>
        public event getTodayLineInfoCompletedEventHandler getTodayLineInfoCompleted;
        
        /// <remarks/>
        public event getBusDepartureScheduleCompletedEventHandler getBusDepartureScheduleCompleted;
        
        /// <remarks/>
        public event GetAllBusLocationCompletedEventHandler GetAllBusLocationCompleted;
        
        /// <remarks/>
        public event GetAllBusLineCompletedEventHandler GetAllBusLineCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10628106.com/bus/getBusLocation", RequestNamespace="http://10628106.com/bus", ResponseNamespace="http://10628106.com/bus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandardDataListOfBusLocationModel getBusLocation(string busLine, string stationName, string lineType, string channelNumber, string channelEncodedKey) {
            object[] results = this.Invoke("getBusLocation", new object[] {
                        busLine,
                        stationName,
                        lineType,
                        channelNumber,
                        channelEncodedKey});
            return ((StandardDataListOfBusLocationModel)(results[0]));
        }
        
        /// <remarks/>
        public void getBusLocationAsync(string busLine, string stationName, string lineType, string channelNumber, string channelEncodedKey) {
            this.getBusLocationAsync(busLine, stationName, lineType, channelNumber, channelEncodedKey, null);
        }
        
        /// <remarks/>
        public void getBusLocationAsync(string busLine, string stationName, string lineType, string channelNumber, string channelEncodedKey, object userState) {
            if ((this.getBusLocationOperationCompleted == null)) {
                this.getBusLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBusLocationOperationCompleted);
            }
            this.InvokeAsync("getBusLocation", new object[] {
                        busLine,
                        stationName,
                        lineType,
                        channelNumber,
                        channelEncodedKey}, this.getBusLocationOperationCompleted, userState);
        }
        
        private void OngetBusLocationOperationCompleted(object arg) {
            if ((this.getBusLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBusLocationCompleted(this, new getBusLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10628106.com/bus/getTodayLineInfo", RequestNamespace="http://10628106.com/bus", ResponseNamespace="http://10628106.com/bus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandardDataListOfLineModel getTodayLineInfo(string busLine, string channelNumber, string channelEncodedKey) {
            object[] results = this.Invoke("getTodayLineInfo", new object[] {
                        busLine,
                        channelNumber,
                        channelEncodedKey});
            return ((StandardDataListOfLineModel)(results[0]));
        }
        
        /// <remarks/>
        public void getTodayLineInfoAsync(string busLine, string channelNumber, string channelEncodedKey) {
            this.getTodayLineInfoAsync(busLine, channelNumber, channelEncodedKey, null);
        }
        
        /// <remarks/>
        public void getTodayLineInfoAsync(string busLine, string channelNumber, string channelEncodedKey, object userState) {
            if ((this.getTodayLineInfoOperationCompleted == null)) {
                this.getTodayLineInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTodayLineInfoOperationCompleted);
            }
            this.InvokeAsync("getTodayLineInfo", new object[] {
                        busLine,
                        channelNumber,
                        channelEncodedKey}, this.getTodayLineInfoOperationCompleted, userState);
        }
        
        private void OngetTodayLineInfoOperationCompleted(object arg) {
            if ((this.getTodayLineInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTodayLineInfoCompleted(this, new getTodayLineInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10628106.com/bus/getBusDepartureSchedule", RequestNamespace="http://10628106.com/bus", ResponseNamespace="http://10628106.com/bus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandardDataListOfBusDepartureModelLine getBusDepartureSchedule(string busLine, string channelNumber, string channelEncodedKey) {
            object[] results = this.Invoke("getBusDepartureSchedule", new object[] {
                        busLine,
                        channelNumber,
                        channelEncodedKey});
            return ((StandardDataListOfBusDepartureModelLine)(results[0]));
        }
        
        /// <remarks/>
        public void getBusDepartureScheduleAsync(string busLine, string channelNumber, string channelEncodedKey) {
            this.getBusDepartureScheduleAsync(busLine, channelNumber, channelEncodedKey, null);
        }
        
        /// <remarks/>
        public void getBusDepartureScheduleAsync(string busLine, string channelNumber, string channelEncodedKey, object userState) {
            if ((this.getBusDepartureScheduleOperationCompleted == null)) {
                this.getBusDepartureScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBusDepartureScheduleOperationCompleted);
            }
            this.InvokeAsync("getBusDepartureSchedule", new object[] {
                        busLine,
                        channelNumber,
                        channelEncodedKey}, this.getBusDepartureScheduleOperationCompleted, userState);
        }
        
        private void OngetBusDepartureScheduleOperationCompleted(object arg) {
            if ((this.getBusDepartureScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBusDepartureScheduleCompleted(this, new getBusDepartureScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10628106.com/bus/GetAllBusLocation", RequestNamespace="http://10628106.com/bus", ResponseNamespace="http://10628106.com/bus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandardData GetAllBusLocation(string channelNumber, string channelEncodedKey) {
            object[] results = this.Invoke("GetAllBusLocation", new object[] {
                        channelNumber,
                        channelEncodedKey});
            return ((StandardData)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBusLocationAsync(string channelNumber, string channelEncodedKey) {
            this.GetAllBusLocationAsync(channelNumber, channelEncodedKey, null);
        }
        
        /// <remarks/>
        public void GetAllBusLocationAsync(string channelNumber, string channelEncodedKey, object userState) {
            if ((this.GetAllBusLocationOperationCompleted == null)) {
                this.GetAllBusLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBusLocationOperationCompleted);
            }
            this.InvokeAsync("GetAllBusLocation", new object[] {
                        channelNumber,
                        channelEncodedKey}, this.GetAllBusLocationOperationCompleted, userState);
        }
        
        private void OnGetAllBusLocationOperationCompleted(object arg) {
            if ((this.GetAllBusLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBusLocationCompleted(this, new GetAllBusLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10628106.com/bus/GetAllBusLine", RequestNamespace="http://10628106.com/bus", ResponseNamespace="http://10628106.com/bus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandardData GetAllBusLine(string channelNumber, string channelEncodedKey) {
            object[] results = this.Invoke("GetAllBusLine", new object[] {
                        channelNumber,
                        channelEncodedKey});
            return ((StandardData)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBusLineAsync(string channelNumber, string channelEncodedKey) {
            this.GetAllBusLineAsync(channelNumber, channelEncodedKey, null);
        }
        
        /// <remarks/>
        public void GetAllBusLineAsync(string channelNumber, string channelEncodedKey, object userState) {
            if ((this.GetAllBusLineOperationCompleted == null)) {
                this.GetAllBusLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBusLineOperationCompleted);
            }
            this.InvokeAsync("GetAllBusLine", new object[] {
                        channelNumber,
                        channelEncodedKey}, this.GetAllBusLineOperationCompleted, userState);
        }
        
        private void OnGetAllBusLineOperationCompleted(object arg) {
            if ((this.GetAllBusLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBusLineCompleted(this, new GetAllBusLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class StandardDataListOfBusLocationModel {
        
        private string codeField;
        
        private string msgField;
        
        private BusLocationModel[] listField;
        
        private string timeStampField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public BusLocationModel[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <remarks/>
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class BusLocationModel {
        
        private string lineTypeField;
        
        private string distanceField;
        
        /// <remarks/>
        public string lineType {
            get {
                return this.lineTypeField;
            }
            set {
                this.lineTypeField = value;
            }
        }
        
        /// <remarks/>
        public string distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class StandardData {
        
        private string codeField;
        
        private string msgField;
        
        private string resultField;
        
        private string timeStampField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class BusDepartureModelLine {
        
        private string finalStationField;
        
        private string departureTimeField;
        
        private string offRunningTimeField;
        
        private string intervalField;
        
        private string lineTypeField;
        
        /// <remarks/>
        public string finalStation {
            get {
                return this.finalStationField;
            }
            set {
                this.finalStationField = value;
            }
        }
        
        /// <remarks/>
        public string departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        public string offRunningTime {
            get {
                return this.offRunningTimeField;
            }
            set {
                this.offRunningTimeField = value;
            }
        }
        
        /// <remarks/>
        public string interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
            }
        }
        
        /// <remarks/>
        public string lineType {
            get {
                return this.lineTypeField;
            }
            set {
                this.lineTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class StandardDataListOfBusDepartureModelLine {
        
        private string codeField;
        
        private string msgField;
        
        private BusDepartureModelLine[] listField;
        
        private string timeStampField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public BusDepartureModelLine[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <remarks/>
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class GPSPoint {
        
        private string longitudeField;
        
        private string latitudeField;
        
        /// <remarks/>
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class StationModel {
        
        private string stationField;
        
        private string stationNumberField;
        
        private GPSPoint gpsPointField;
        
        /// <remarks/>
        public string station {
            get {
                return this.stationField;
            }
            set {
                this.stationField = value;
            }
        }
        
        /// <remarks/>
        public string stationNumber {
            get {
                return this.stationNumberField;
            }
            set {
                this.stationNumberField = value;
            }
        }
        
        /// <remarks/>
        public GPSPoint gpsPoint {
            get {
                return this.gpsPointField;
            }
            set {
                this.gpsPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class LineModel {
        
        private string departureTimeField;
        
        private string offRunningTimeField;
        
        private string lineTypeField;
        
        private StationModel[] stationsField;
        
        /// <remarks/>
        public string departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        public string offRunningTime {
            get {
                return this.offRunningTimeField;
            }
            set {
                this.offRunningTimeField = value;
            }
        }
        
        /// <remarks/>
        public string lineType {
            get {
                return this.lineTypeField;
            }
            set {
                this.lineTypeField = value;
            }
        }
        
        /// <remarks/>
        public StationModel[] stations {
            get {
                return this.stationsField;
            }
            set {
                this.stationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10628106.com/bus")]
    public partial class StandardDataListOfLineModel {
        
        private string codeField;
        
        private string msgField;
        
        private LineModel[] listField;
        
        private string timeStampField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public LineModel[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <remarks/>
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getBusLocationCompletedEventHandler(object sender, getBusLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBusLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBusLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandardDataListOfBusLocationModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandardDataListOfBusLocationModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getTodayLineInfoCompletedEventHandler(object sender, getTodayLineInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTodayLineInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTodayLineInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandardDataListOfLineModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandardDataListOfLineModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getBusDepartureScheduleCompletedEventHandler(object sender, getBusDepartureScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBusDepartureScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBusDepartureScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandardDataListOfBusDepartureModelLine Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandardDataListOfBusDepartureModelLine)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllBusLocationCompletedEventHandler(object sender, GetAllBusLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBusLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBusLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandardData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandardData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllBusLineCompletedEventHandler(object sender, GetAllBusLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBusLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBusLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandardData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandardData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591